### ISSUE TITLE
Cant config module for dolibarr

### ISSUE THREAD

**Issue by pastrikosko-zz** [SplashSync/Dolibarr#1]
Im facing this error during the installation of dolibarr module

Errors
Server Path is Empty (Path of Splash webservice file on your server - soap.php)
ErrEmptyServerPathDesc

Where can i define the requested path?
Thank you in advance

**Comment by BadPixxel** [comment]
Hi,

Thank for using Splash!

Two points:
- you are using dolibarr on a local server... Doesn't work.
- there is no way to 'change' this parameter, it's taken directly from
server info.

I think you should push your install of dolibarr on an hosted server, even
if just for testing our service.

Let me know if you need any help. I'll take more care upon next week.

Best regards
