### ISSUE TITLE
Trying to install and setup Splash on Dolibarr 17

### ISSUE THREAD

**Issue by codefreak558** [SplashSync/Dolibarr#14]
I am currently trying to set up and configure Splash for Dolibarr so that I can use it along with my woocommerce site so the woocommerce one works but when it comes to the dolibarr one that doesn't work the local selftest works but it looks like when it trys to do the connect it doesn't work

 `Errors
[Splash Client] [WS] Aucune réponse à la requête (Service "Connect", Url "https://erp.fettlen.co.za/custom/splash/vendor/splash/phpcore/soap.php")
[Splash Client] Self Connect of your server Fail (Tested Url : https://erp.fettlen.co.za/custom/splash/vendor/splash/phpcore/soap.php)
[Splash Client] More details here : https://erp.fettlen.co.za/custom/splash/vendor/splash/phpcore/soap.php`
This is the error that I get when I try using it on dolibarr I do already have a the unique identifier along with the encryption key but that doesn't work.

Any ideas?

**Comment by vdegrandpre** [comment]
I can confirm that the splash connector is broken on Dolibarr v17.

I have a fresh install of dolibarr v17 and Splash connector latest (1.16.0). I am receiving the same error message as @codefreak558 when trying to connect.

Then, I took a working instance of Splash connector v 1.15 with dolibarr v 16.0. The connection was working (refreshing in the Splash dashboard is OK). Then I upgraded Dolibarr to v 17.0.1 and to Splash connector v 1.16.0. Still it was working. Then I deactivated the server in Splash dashboard and I now get this error trying to reconnect it : 

![Capture d’écran de 2023-04-17 12-26-24](https://user-images.githubusercontent.com/3855975/232550142-0564afa1-bd9f-4f7b-a7c1-e555ef57b87d.png)

Can you estimate when it can be fixed ?

Thanks

**Comment by BadPixxel** [comment]
Hi

Can you please try our latests reslease: https://github.com/SplashSync/Dolibarr/releases/tag/2.17.0

We had many smal fixes to solve before releasing this new version.
Impatiant to read your feedbacks.

BR

**Comment by Saunio4** [comment]
Hello,

I have the same issue with Dolibarr v17 and the 1.16.0 version of splash module. I just tried to update to version 2.17.0 and the issue is the same for me.
![image](https://user-images.githubusercontent.com/119810133/234879631-1479d074-960b-426b-a1f5-83bd0fced821.png)

**Comment by codefreak558** [comment]
Hi,

I have tried using v2.17.0 and it unfortunatly still gives the same issue.

![Screenshot_20230430_160450](https://user-images.githubusercontent.com/46318596/235357229-0e734c14-5a99-40d6-9b8c-61b07fa02bca.png)

**Comment by vdegrandpre** [comment]
Same here, we still have the same problems and SplashSync indicate that it cannot connect to the server.

Is there any prerequisites or requirements we are missing ?

**Note** : Hosted on WHM/cPanel.

**Comment by vdegrandpre** [comment]
@BadPixxel can you estimate the source of error and the availability of the fix ?

**Comment by Mikojevic** [comment]
Hello Guys,

Does this issue is fixed?

Cheers,

Mario.

**Comment by codefreak558** [comment]
Hi Mario,

I will download the new update v2.17.1 and take a look

**Comment by codefreak558** [comment]
![firefox_gjtbZ3j5C8](https://github.com/SplashSync/Dolibarr/assets/46318596/973eb059-a4f0-4e62-ab70-46f134f6c41e)

Yes it seems to be working now. It's not giving any of the errors it was giving last time. I have yet to test syncing with other services but as it looks now I can say it is working.
