### ISSUE TITLE
Install to /custom not working

### ISSUE THREAD

**Issue by swedebugia** [SplashSync/Dolibarr#5]
Hi.
I installed splash and it did not find the icon and I got a 404-error when trying to configure it.
After copying /splash to the /usr/share/webapps/dolibarr/htdocs/ dir it worked like a charm.
I consider this an error as 3rd party modules should not be placed there.

**Comment by BadPixxel** [comment]
Hi,

Which version did you use? Any dolibarr version? 

 Install to custom is the standard behavior for this module.

BR
