### ISSUE TITLE
Local server warning

### ISSUE THREAD

**Issue by swedebugia** [SplashSync/Dolibarr#6]
Hi
I test installed splash to my dolibarr running on my parabola gnu/linux desktop machine.
I have UFW enabled to block all incoming connections.
I got this warning
"Warning
Your have installed this module on a Local Server, Splash cannot to connect it."
Should I change something to make it work?

**Comment by BadPixxel** [comment]
Hi,

Yes... Just install and access your module on a server we can access from web.

We need a public url to access our modules, even with http Auth. Here Ssplah detect your are on a local machine, this is strictly what we expected. :-) 

For general user support, please use our live tchat or contact page.

Best regards
