### ISSUE TITLE
Trigger traits : DoliDB::commit() messes with current transactions

### ISSUE THREAD

**Issue by ATM-Marc** [SplashSync/Dolibarr#7]
Your trigger code makes a solitary call to DoliDB::commit().

DoliDB instance keeps count of the nesting of database transactions and only really begins, commits, or rolls back the outer one.

As a consequence, there are more calls to commit() or rollback() than to begin(). This prevents the outer transaction to be rolled back if there was an error somewhere else (a lower priority trigger, for example).

**Comment by xfred81** [comment]
Hey,

I'm not specialist but I got an issue with latest Dolibarr here which seems related to problem described by @ATM-Marc :
`Error, the balance begin/close of db transactions has been broken into trigger InterfaceSplash with action=PRODUCT_MODIFY before=1 after=0`

This prevents all synchronizations.

**Comment by BadPixxel** [comment]
Hi,

This error was fixed weeks ago, please upgrade your modules to [V1.8.2](https://github.com/SplashSync/Dolibarr/releases/tag/1.8.2)

Best regards,

**Comment by xfred81** [comment]
Hey

@BadPixxel, tyvm. Yet, for information, Dolistore only proposes 1.6.0:
https://www.dolistore.com/fr/modules/789-Connecteur-Splash-Sync.html?search_query=splash&results=1

**Comment by BadPixxel** [comment]
@xfred81 I'll update Dolistore soon. Thx
